### ISSUE TITLE
Atualização do readme.

### ISSUE THREAD

**Issue by fvieir** [lilian-rangel/Projeto-formulario-de-cadastro#1]
Ola Lilian, como vai?

Conforme deixado o Feedback e orientações no Discord, segue minha solicitação para atualização do readme.

Qualquer duvida é so chamar.

Forte abraço

**Comment by lilian-rangel** [comment]
Olá, Fabrício.

Atualização do readme realizada conforme recomendação pelo discord.
Aguardo validação.

**Comment by fvieir** [comment]
Excelente, obrigado.

**Comment by lilian-rangel** [comment]
Atualização do readme feita conforme recomendação do tutor Fabrício.
