### ISSUE TITLE
Estrtutura de pastas.

### ISSUE THREAD

**Issue by fvieir** [lilian-rangel/Projeto-formulario-de-cadastro#2]
Ola Lilian, como vai?

Conforme deixado o Feedback e orientações no Discord, segue minha solicitação para estrtutura das pastas.

Segue uma ideia de como estruturar.

![image](https://user-images.githubusercontent.com/65264206/196414235-35e7d046-da1a-42d8-8206-bbc0b86641af.png)

Qualquer duvida é so chamar.

**Comment by lilian-rangel** [comment]
Olá, Fabrício. Estou bem e você?

Os ajustes solicitados foram feitos conforme orientação.

**Comment by fvieir** [comment]
Ótimo, parabéns 💯 .
